name: file_picker
description: A plugin that allows you to pick absolute paths from diferent file types.
version: 1.2.0
author: Miguel Ruivo <miguelpruivo@outlook.com>
homepage: https://github.com/miguelpruivo/plugins_flutter_file_picker


dependencies:
  flutter:
    sdk: flutter
  image_picker:
          git:
           url: https://github.com/tukaramc/image_picker.git
           ref: b104b676d8592e8fdc5fd9aae9d728fefd210d30
  meta: ^1.1.5

environment:
  sdk: ">=2.0.0 <3.0.0"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: com.mr.flutter.plugin.filepicker
    pluginClass: FilePickerPlugin

